python-targets:
  - 2
  - 3
pep8:
  full: true
strictness: veryhigh
pylint:
  disable:
    - no-self-argument
    - R0201
    - invalid-name
    - unused-argument
    - global-variable-not-assigned
    - bad-classmethod-argument
    - protected-access
    - broad-except
    - too-many-arguments
    - too-few-public-methods
    - arguments-differ
    - anomalous-backslash-in-string
    - global-statement
mccabe:
  disable:
    - MC0001
pyflakes:
  disable:
    - F401
