sudo: False
language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev"
install: 
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script: 
  - coverage run test.py
on_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
