sudo: False
language: python
cache: pip
python:
  - "2.7.13"
  - "3.3.5"
  - "3.4.5"
  - "3.5.2"
  - "3.6.1"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage python-coveralls
script:
  - coverage run test.py --source="test.py,plugins/*.py,utils/*.py,ansi.py,config.py,handlers.py,log.py" --parallel-mode --timid
after_success:
  - coverage combine
  - coverage report --include="test.py,plugins/*.py,utils/*.py,ansi.py,config.py,handlers.py,log.py" --omit="utils/tasks.py,utils/web.py"
  - coverage xml --include="test.py,plugins/*.py,utils/*.py,ansi.py,config.py,handlers.py,log.py" --omit="utils/tasks.py,utils/web.py"
  - python-codacy-coverage -r coverage.xml
  - coveralls
