sudo: False
language: python
cache: pip
python:
  - "2.7.13"
  - "3.3.5"
  - "3.4.5"
  - "3.5.2"
  - "3.6.0"
  - "nightly"
install: 
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script: 
  - coverage run test.py
after_success:
  - coverage report
  - coverage xml
  - python-codacy-coverage -r coverage.xml
