sudo: False
language: python
cache: pip
python:
  - "2.7.14"
  - "3.3.6"
  - "3.4.6"
  - "3.5.4"
  - "3.6.4"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install coverage codacy-coverage
script:
  - touch userdb.json
  - echo '{}' > userdb.json
  - coverage run test.py --source="test.py,plugins/*.py,utils/*.py,ansi.py,config.py,handlers/*.py,log.py" --exclude="utils/tasks.py,utils/web.py,handlers/server.py"
after_success:
  - coverage report --include="test.py,plugins/*.py,utils/*.py,ansi.py,config.py,handlers/*.py,log.py" --omit="utils/tasks.py,utils/web.py,handlers/server.py"
  - coverage xml --include="test.py,plugins/*.py,utils/*.py,ansi.py,config.py,handlers/*.py,log.py" --omit="utils/tasks.py,utils/web.py,handlers/server.py"
  - python-codacy-coverage -r coverage.xml
